version: '3'

services:
  # postgres:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: none
    ports:
      - 1025:1025
      - 8025:8025
